import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./[components]/Header";
import Footer from "./[components]/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "M.I.A | Home",
  description: "Generated by M.I.A | Home",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} text-white text-center flex flex-col relative  body bg-gray-900 min-h-screen`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
